language: python
python:
- '3.7'
script: true
deploy:
  provider: pypi
  user: mojikimino
  on:
    tags: true
  password:
    secure: VADTBd3BaZ9HgNbhsKBEdL6jiqTsLKgdoU5qq6sCfbAWkJHYi78v+HWiJ7OHFpUY4iLpi3k/vpHRYkPA/OtMxTcA6BCxTYGWzs6Z9ndPf32YsuxeOFDbfa2cjSnIgCBVo2m7Nf/BhD/yTBtlY1NBGlL1R6kBrZvd1B/SoK5tTExZkkkhYT4J2Rmxhog15xSmYebPoXnRFslw9gZfsda0moTe89v8Nr3FNNHz8ikYOlt6vbStJLtr0Xnrxy1ggMreSEPKVLPcblNuSNH/mRnMJe+aHAZzUSpoHCsMjjg+yGNtZlpX5UhY2Xw/SUiM8u3BySb8FU5rQDr2fuY+ukcWZap2qvshwJW0qrHEW3Coy5Fp0N0i1Z3Lg47jkWVezvWwPkAjTWWfCYP9NpR+3b4+6bHM4wgIv9Ad+cdWlRSDz5aS+Wx3rfc2UnRerAYXduCDZR1uq27XznT2FtPAHyEG2GD6FeRxIfxmM5A1O2A9NIHE/4tgo/DYWam7iDXHu/fOc7Y14MnpktdJt+SiDEr1LC8+uJfwhmT8ECdSvi7+mNG0SXiwIAXNFj9RhvfFZuYMDgdsfw8JQcfgmdi2jp6HJBbGKkReN2Zv1u5Kmik5D84OkpYHov/KW3kc0+4Pxqd74StI/jJdjwNDyecxKUjGO9aykGHAu0PfAcL76xZK/Ac=
